language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then travis_retry pip install ordereddict; fi

script: nosetests -s -v -with-coverage --cover-branches --cover-package=pylogops
 