language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip freeze

script: nosetests -s -v --with-coverage --cover-branches --cover-package=pylogops
 